spring:
  application:
    name: ex-oauth2-demo
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.149:8282/realms/dionext
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.1.149:8282/realms/dionext
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: {MY_CLIENT_NAME}
            client-secret: {MY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
logging:
  config: classpath:${LOGBACK:logback-local.xml}
  level:
    root: info
    com:
      dionext: debug